@startuml blackjack_class
Together {
    Abstract class Member {
        # seq[Card] hand
        # Score score
        # Reset()
        # CalculateScore()
        # IsBurst()
        # PrintHands()
        - SuitToString()
        - NumberToString()
    }
    Class Player {
        - ReceiveCard()
    }
    Class Dealer {
        - GetStock()
        - DealCards()
        - GetCard()
        - ShuffleStock()
        - TurnUpHand()
    }
}
Together {
    Class Card {
        Suit suit
        Number Number
        bool isUp
    }
Class Stock {
        seq[Card] card
    }
}

Member <|-- Player
Member <|-- Dealer

Stock <-- Dealer
Stock *-- Card
Stock <-- Stock : Singleton

@enduml